apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-profile
  description: customer-profile
  tags:
    - java
    - rest
    - cloud
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=customer-profile'
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://customer-profile.apps.lab.synable.io/api-docs
      title: 'Customer Profile API Docs'
      icon: locallibrary
spec:
  type: service
  lifecycle: experimental
  owner: tas-dev-ex
  system: demo
  apiProvidedBy:
    - customer-profile-api
  links:
    - url: https://customer-profile.apps.lab.synable.io/api-docs
      title: 'Customer Profile API Docs'
      icon: locallibrary
