apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tas-dev-ex
  description: TAS Developer Experiences Team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: development
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jlafata
spec:
  profile:
    displayName: John LaFata
    email: john.lafata@broadcom.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [tas-dev-ex]